-- auto-generated definition
create table ic_user.users
(
    id         bigint generated by default as identity
        constraint pk_users
            primary key,
    first_name text,
    last_name  text,
    email      text,
    password   text
);

alter table ic_user.users
    owner to postgres;

