create table internships
(
    id            bigint generated by default as identity
        constraint pk_internships
            primary key,
    company_id    bigint
        constraint fk_internships_companies_company_id
            references companies
            on delete restrict,
    position_name text,
    domain        integer          not null,
    description   text,
    recruiter_id  bigint default 0 not null
);

alter table internships
    owner to postgres;

create index ix_internships_company_id
    on internships (company_id);

