create table applications
(
    id            bigint generated by default as identity
        constraint pk_applications
            primary key,
    internship_id bigint  not null,
    student_id    bigint  not null,
    status        integer not null
);

alter table applications
    owner to postgres;

