create table profiles
(
    id          bigint generated by default as identity
        constraint pk_profiles
            primary key,
    user_id     bigint not null,
    description text
);

alter table profiles    
    owner to postgres;




create table profile_sections
(
    id         bigint generated by default as identity
        constraint pk_profile_sections
            primary key,
    profile_id bigint not null
        constraint fk_profile_sections_profiles_profile_id
            references profiles
            on delete cascade,
    name       text,
    position   bigint not null
);

alter table profile_sections
    owner to postgres;

create index ix_profile_sections_profile_id
    on profile_sections (profile_id);




create table profile_section_entries
(
    id                 bigint generated by default as identity
        constraint pk_profile_section_entries
            primary key,
    profile_section_id bigint not null
        constraint fk_profile_section_entries_profile_sections_profile_section_id
            references profile_sections
            on delete cascade,
    position           bigint not null
);

alter table profile_section_entries
    owner to postgres;

create index ix_profile_section_entries_profile_section_id
    on profile_section_entries (profile_section_id);




create table profile_section_fields
(
    id                 bigint generated by default as identity
        constraint pk_profile_section_fields
            primary key,
    profile_section_id bigint  not null
        constraint fk_profile_section_fields_profile_sections_profile_section_id
            references profile_sections
            on delete cascade,
    name               text,
    kind               integer not null
);

alter table profile_section_fields
    owner to postgres;

create index ix_profile_section_fields_profile_section_id
    on profile_section_fields (profile_section_id);




create table profile_section_entry_data
(
    id                       bigint generated by default as identity
        constraint pk_profile_section_entry_data
            primary key,
    profile_section_entry_id bigint not null
        constraint fk_profile_section_entry_data_profile_section_entries_profile_s
            references profile_section_entries
            on delete cascade,
    name                     text,
    value                    text
);

alter table profile_section_entry_data
    owner to postgres;

create index ix_profile_section_entry_data_profile_section_entry_id
    on profile_section_entry_data (profile_section_entry_id);

