version: "3.7"

services:
  postgres:
    image: interncaptain-postgres:latest
    volumes:
      - postgres_volume:/home/postgres/volume
    environment: 
      POSTGRES_PASSWORD: 'pass'
      POSTGRES_USER: 'postgres'
      POSTGRES_DB: 'interncaptain'
    ports:
      - 5432:5432

volumes:
  postgres_volume: